// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_qTEtuaUrK_AfAnIlrUnqORvaB7zvrDo',
    appId: '1:451583045095:web:05a22f5cd14709506aa142',
    messagingSenderId: '451583045095',
    projectId: 'ecommerce-flutter-20022',
    authDomain: 'ecommerce-flutter-20022.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-20022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDsDyLYifnVIuQ51Akdz-aqN5RROe1aYs',
    appId: '1:451583045095:android:cda93655aecfdb766aa142',
    messagingSenderId: '451583045095',
    projectId: 'ecommerce-flutter-20022',
    storageBucket: 'ecommerce-flutter-20022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB12beTJGDixCmLd2lbd_o3oBzAiGMNU0',
    appId: '1:451583045095:ios:fa5087307e475ff86aa142',
    messagingSenderId: '451583045095',
    projectId: 'ecommerce-flutter-20022',
    storageBucket: 'ecommerce-flutter-20022.appspot.com',
    iosClientId: '451583045095-id3e57tu5c93vi8ic66orb2vbbounevr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB12beTJGDixCmLd2lbd_o3oBzAiGMNU0',
    appId: '1:451583045095:ios:fa5087307e475ff86aa142',
    messagingSenderId: '451583045095',
    projectId: 'ecommerce-flutter-20022',
    storageBucket: 'ecommerce-flutter-20022.appspot.com',
    iosClientId: '451583045095-id3e57tu5c93vi8ic66orb2vbbounevr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
